import {
  type CommandIO, InputFieldType, type InputSchema, PluginCommand, schemaToArgs, schemaToFlags,
} from '@metamask/agent-wallet/plugin';
import { encodeFunctionData, parseEventLogs } from 'viem';
import { ERC8004_IDENTITY_TESTNET, identityAbi, registrationUri } from '../../../../../packages/grain-core/src/index.ts';
import { registryClient, selectedAddress, SITE } from '../../lib/grain.ts';
import { ensureMonadTestnetRpc, executorRequest } from '../../lib/submit.ts';

/**
 * Give this agent an ERC-8004 identity on Monad testnet.
 *
 * Mints an agent id on the standard IdentityRegistry, owned by this MetaMask
 * wallet, with its registration file (name, description) embedded as a data:
 * URI. Images the agent then registers with `mm grain register --agent-id`
 * are shown as "AI-generated by <name>", checked on chain.
 */

const inputs = {
  name: { type: InputFieldType.Text, flag: 'name', index: 0, required: true, prompt: true, message: "The agent's name, e.g. Studio Bot" },
  description: { type: InputFieldType.Text, flag: 'description', required: false, prompt: false, message: 'What the agent does' },
} satisfies InputSchema;

type AgentResult = { agentId: string | null; name: string; owner: string | null; hash?: string; status?: string; failureReason?: string };

export default class GrainAgent extends PluginCommand<AgentResult> {
  static override description = 'Create an ERC-8004 agent identity for this wallet on Monad testnet, so images it generates are credited to it.';
  static override examples = ['<%= config.bin %> grain agent "Studio Bot" --description "Generates product illustrations"'];
  static override flags = schemaToFlags(inputs);
  static override args = schemaToArgs(inputs);
  protected readonly pluginCommandId = 'grain:agent';

  async execute(io: CommandIO): Promise<AgentResult> {
    const { name, description } = await io.resolveInputs(inputs);
    const agentName = String(name).trim().slice(0, 80);
    if (!agentName) throw new Error('Give the agent a name.');
    const uri = registrationUri({
      name: agentName,
      description: description ? String(description).slice(0, 280) : undefined,
      services: [{ name: 'grain', endpoint: SITE }],
    });
    if (ensureMonadTestnetRpc(this.ctx.walletStateManager as never)) {
      io.progress("Pointed MetaMask at Monad testnet's own RPC (its default proxy rejects chain 10143)");
    }
    const executor = await this.ctx.walletExecutor(io, 'grain:agent');
    const result = (await executor(
      (await executorRequest(10143, {
        to: ERC8004_IDENTITY_TESTNET,
        value: '0x0',
        data: encodeFunctionData({ abi: identityAbi, functionName: 'register', args: [uri] }),
      }, { action: 'custom', summary: `Create the ERC-8004 agent identity "${agentName}" on Monad testnet` })) as never,
      { signal: io.signal } as never,
    )) as { status?: string; hash?: `0x${string}`; failureDescription?: string };

    let agentId: string | null = null;
    if (result.hash) {
      io.progress('Waiting for the agent id');
      const receipt = await registryClient().waitForTransactionReceipt({ hash: result.hash });
      const [registered] = parseEventLogs({ abi: identityAbi, logs: receipt.logs, eventName: 'Registered' });
      agentId = registered?.args.agentId?.toString() ?? null;
      io.progress();
    }
    return {
      agentId, name: agentName, owner: selectedAddress(this.ctx.walletStateManager.read() as never),
      hash: result.hash, status: result.status, failureReason: result.failureDescription,
    };
  }

  override successHint(r: AgentResult): string {
    if (r.failureReason || !r.agentId) return `The agent identity was not created${r.failureReason ? `: ${r.failureReason}` : '.'}`;
    return `Created ERC-8004 agent #${r.agentId} "${r.name}", owned by ${r.owner}.\nRegister its images with: mm grain register <image> --agent-id ${r.agentId}${r.hash ? `\nTransaction: https://testnet.monadscan.com/tx/${r.hash}` : ''}`;
  }
}
