import {
  type CommandIO, InputFieldType, type InputSchema, PluginCommand, schemaToArgs, schemaToFlags,
} from '@metamask/agent-wallet/plugin';
import { encodeFunctionData, zeroHash } from 'viem';
import { ERC8004_IDENTITY_TESTNET, ERC8004_REPUTATION_TESTNET, reputationAbi } from '../../../../../packages/grain-core/src/index.ts';
import { agentIdentity, recordAgent, registryClient, selectedAddress } from '../../lib/grain.ts';
import { MONAD_TESTNET, planLicence, type LicencePlan } from '../../lib/payment.ts';
import { who } from '../../lib/format.ts';
import { ensureMonadTestnetRpc, executorRequest } from '../../lib/submit.ts';

/**
 * License an image through Grain's LicenseRegistry on Monad testnet.
 *
 * Unlike `pay`, the price is the creator's, not the agent's: they set it when
 * they registered. The contract forwards it in full to them -- there is no
 * protocol fee -- and records the licence on chain, where anyone (and Grain's
 * Envio indexer) can see the agent paid.
 *
 * With --rate, and when the image was generated by an ERC-8004 agent whose
 * identity checks out, the licensee then leaves that agent feedback on the
 * standard ReputationRegistry: a paid licence is the strongest signal an
 * agent's work is any good.
 */

const inputs = {
  target: {
    type: InputFieldType.Text, flag: 'target', index: 0, required: true, prompt: true,
    message: 'The image (path or URL) to license, or a Grain record number',
  },
  maxPrice: {
    type: InputFieldType.Text, flag: 'max-price', required: false, prompt: false,
    message: 'Refuse if the creator asks more than this, in MON. Recommended for unattended agents',
  },
  rate: {
    type: InputFieldType.Text, flag: 'rate', required: false, prompt: false,
    message: 'After licensing, rate the ERC-8004 agent that generated the image, 1-5',
  },
  dryRun: {
    type: InputFieldType.Boolean, flag: 'dry-run', required: false, prompt: false,
    message: 'Show the price and the transaction without sending it',
  },
} satisfies InputSchema;

type Rating = { agentId: string; agentName?: string; score?: number; hash?: string; skipped?: string };
type LicenceResult = LicencePlan & { sent: boolean; status?: string; hash?: string; failureReason?: string; rating?: Rating };

export default class GrainLicense extends PluginCommand<LicenceResult> {
  static override description =
    "License an image at its creator's price, paid to them through Grain's LicenseRegistry and recorded on chain.";

  static override examples = [
    '<%= config.bin %> grain license https://grain-on-monad.vercel.app/samples/reposted.jpg --max-price 0.05',
    '<%= config.bin %> grain license 511 --dry-run --json',
    '<%= config.bin %> grain license 534 --max-price 0.05 --rate 5',
  ];

  static override flags = schemaToFlags(inputs);
  static override args = schemaToArgs(inputs);
  protected readonly pluginCommandId = 'grain:license';

  async execute(io: CommandIO): Promise<LicenceResult> {
    const { target, maxPrice, rate, dryRun } = await io.resolveInputs(inputs);
    const score = rate === undefined || rate === '' ? null : Number(rate);
    if (score !== null && !(Number.isInteger(score) && score >= 1 && score <= 5)) throw new Error('--rate is a whole number from 1 to 5.');
    const plan = await planLicence(String(target), maxPrice ? String(maxPrice) : undefined, (l) => io.progress(l));
    if (dryRun) return { ...plan, sent: false };

    if (plan.chainId === MONAD_TESTNET && ensureMonadTestnetRpc(this.ctx.walletStateManager as never)) {
      io.progress('Pointed MetaMask at Monad testnet\'s own RPC (its default proxy rejects chain 10143)');
    }
    const executor = await this.ctx.walletExecutor(io, 'grain:license');
    const result = (await executor(
      (await executorRequest(plan.chainId, plan.transaction, {
        action: 'custom',
        summary: `License Grain record #${plan.recordId} from ${plan.creatorHandle ? `@${plan.creatorHandle}` : plan.creator} for ${plan.price} MON, paid in full to the creator`,
      })) as never,
      { signal: io.signal } as never,
    )) as { status?: string; hash?: `0x${string}`; failureDescription?: string };
    const licensed = { ...plan, sent: true, status: result.status, hash: result.hash, failureReason: result.failureDescription };
    if (score === null || !result.hash || plan.chainId !== MONAD_TESTNET) return licensed;

    // Rate only once the licence is final, and only an agent whose identity checks out.
    io.progress('Waiting for the licence to confirm');
    const receipt = await registryClient().waitForTransactionReceipt({ hash: result.hash });
    io.progress();
    if (receipt.status !== 'success') return { ...licensed, failureReason: 'the licence transaction reverted' };
    return { ...licensed, rating: await this.rate(io, executor, BigInt(plan.recordId), score) };
  }

  private async rate(io: CommandIO, executor: (r: never, o: never) => Promise<unknown>, recordId: bigint, score: number): Promise<Rating | undefined> {
    const agent = await recordAgent(recordId);
    if (!agent) return undefined;
    const base = { agentId: agent.agentId, agentName: agent.name };
    if (!agent.verified) return { ...base, skipped: "the record's creator doesn't control that agent, so it wasn't rated" };
    // The ReputationRegistry refuses feedback from the agent's own owner.
    const me = selectedAddress(this.ctx.walletStateManager.read() as never);
    const identity = await agentIdentity(ERC8004_IDENTITY_TESTNET, BigInt(agent.agentId));
    if (identity && me && identity.owner.toLowerCase() === me.toLowerCase()) return { ...base, skipped: "an agent can't rate itself" };
    const r = (await executor(
      (await executorRequest(MONAD_TESTNET, {
        to: ERC8004_REPUTATION_TESTNET,
        value: '0x0',
        data: encodeFunctionData({
          abi: reputationAbi, functionName: 'giveFeedback',
          args: [BigInt(agent.agentId), BigInt(score), 0, 'grain-licence', 'image', `https://grain-on-monad.vercel.app/r/${recordId}`, '', zeroHash],
        }),
      }, { action: 'custom', summary: `Rate ERC-8004 agent #${agent.agentId}${agent.name ? ` "${agent.name}"` : ''} ${score}/5 for Grain record #${recordId}` }, me)) as never,
      { signal: io.signal } as never,
    )) as { hash?: string; failureDescription?: string };
    return r.hash ? { ...base, score, hash: r.hash } : { ...base, skipped: r.failureDescription ?? 'the rating was not sent' };
  }

  override successHint(r: LicenceResult): string {
    const to = who({ creatorHandle: r.creatorHandle ?? undefined, creator: r.creator });
    if (!r.sent) return `Licensing record ${r.recordId} costs ${r.price} MON, paid in full to ${to}. Nothing was sent.`;
    if (r.failureReason) return `The licence did not go through: ${r.failureReason}`;
    const agent = r.rating && `ERC-8004 agent #${r.rating.agentId}${r.rating.agentName ? ` "${r.rating.agentName}"` : ''}`;
    const rating = !r.rating ? '' : r.rating.hash
      ? `\nRated ${agent} ${r.rating.score}/5: https://testnet.monadscan.com/tx/${r.rating.hash}`
      : `\nDid not rate ${agent}: ${r.rating.skipped}`;
    return `Licensed record ${r.recordId} from ${to} for ${r.price} MON.${r.hash ? `\nTransaction: ${r.chainId === 10143 ? `https://testnet.monadscan.com/tx/${r.hash}` : r.hash}` : ''}\n${r.recordUrl}${rating}`;
  }
}
