/**
 * Makes @grain-studio an ERC-8004 agent and registers an image it generated.
 *
 * 1. Mints an ERC-8004 identity on Monad testnet's IdentityRegistry for the
 *    @grain-studio account, with its registration file embedded as a data:
 *    URI ("Grain Studio Agent"). Once: the agent id is kept in .env.
 * 2. Registers the aurora artwork the way the register page would --
 *    watermark with the next record id, fingerprint the marked image, sign,
 *    register -- with the manifest declaring it AI-generated by that agent.
 *
 * Verify then reads "AI-generated by Grain Studio Agent (agent #N)", and
 * checks on chain that the record's signer controls agent #N.
 *
 *   npx esbuild scripts/register-agent-sample.ts --bundle --platform=node --format=esm \
 *     --alias:onnxruntime-web/wasm=onnxruntime-web --external:onnxruntime-web \
 *     --outfile=plugins/mm-grain/.ras.mjs && node plugins/mm-grain/.ras.mjs
 */
import { appendFileSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createPublicClient, createWalletClient, http, parseAbi, parseEventLogs, type Hex } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import {
  buildManifest, decodeImage, encodePNG, encodeSignedManifest, fingerprint, signManifest,
  DIGITAL_SOURCE, ERC8004_IDENTITY_TESTNET, identityAbi, registrationUri,
} from '../packages/grain-core/src/index.ts';
import { encodeWatermark, useModelBytes } from '../apps/web/app/lib/trustmark/index.ts';

const ROOT = process.cwd();
const AGENT_NAME = 'Grain Studio Agent';
const SOURCE = join(ROOT, '.corpus', 'samples', 'aurora.png');
const OUT = join(ROOT, '.corpus', 'samples', 'aurora-grain.png');

const envFile = join(ROOT, '.env');
const env = Object.fromEntries(readFileSync(envFile, 'utf8').split('\n')
  .filter((l) => l.includes('=') && !l.trimStart().startsWith('#'))
  .map((l) => [l.slice(0, l.indexOf('=')).trim(), l.slice(l.indexOf('=') + 1).trim()]));
const key = env.SAMPLES_PRIVATE_KEY as Hex;
const studio = privateKeyToAccount(key);
const D = JSON.parse(readFileSync(join(ROOT, 'deployments', 'monad-testnet.json'), 'utf8'));
const chain = { id: 10143, name: 'Monad Testnet', nativeCurrency: { name: 'MON', symbol: 'MON', decimals: 18 },
  rpcUrls: { default: { http: [env.RPC_TESTNET_ENDPOINT] } } } as const;
const transport = http(env.RPC_TESTNET_ENDPOINT);
const pub = createPublicClient({ chain, transport });
const wallet = createWalletClient({ account: studio, chain, transport });
const registryAbi = parseAbi([
  'function register(uint64 expectedRecordId, uint64 fingerprint, bytes manifest) returns (uint64)',
  'function nextRecordId() view returns (uint64)',
]);

// 1. The agent's ERC-8004 identity.
let agentId = env.STUDIO_AGENT_ID ? BigInt(env.STUDIO_AGENT_ID) : null;
if (agentId === null) {
  const uri = registrationUri({
    name: AGENT_NAME,
    description: 'An AI agent that generates artwork and registers every piece on Grain, so copies of it can always be traced back.',
    services: [{ name: 'web', endpoint: 'https://grain-on-monad.vercel.app/c/grain-studio' }],
  });
  const hash = await wallet.writeContract({ address: ERC8004_IDENTITY_TESTNET, abi: identityAbi, functionName: 'register', args: [uri] });
  const receipt = await pub.waitForTransactionReceipt({ hash });
  const [registered] = parseEventLogs({ abi: identityAbi, logs: receipt.logs, eventName: 'Registered' });
  agentId = registered.args.agentId;
  appendFileSync(envFile, `\n# ERC-8004 agent id of @grain-studio (scripts/register-agent-sample.ts)\nSTUDIO_AGENT_ID=${agentId}\n`);
  console.log(`minted ERC-8004 agent #${agentId} (${AGENT_NAME})  tx ${hash}`);
  await new Promise((r) => setTimeout(r, 2000)); // Monad's delayed state, before the next tx
} else {
  console.log(`using ERC-8004 agent #${agentId}`);
}

// 2. Register the aurora as generated by that agent.
const M = join(ROOT, 'apps', 'web', 'public', 'models');
useModelBytes({ encoder: readFileSync(join(M, 'encoder_Q.onnx')), resizer: readFileSync(join(M, 'resizer.onnx')) });
const recordId = await pub.readContract({ address: D.contracts.GrainRegistry, abi: registryAbi, functionName: 'nextRecordId' });
const marked = await encodeWatermark(decodeImage(new Uint8Array(readFileSync(SOURCE))), recordId);
writeFileSync(OUT, encodePNG(marked));
const fp = fingerprint(marked);
const manifest = await signManifest(buildManifest({
  recordId, creator: studio.address, fingerprint: fp, watermarked: true,
  title: 'Aurora',
  generator: 'Grain Studio Agent (scripts/register-agent-sample.ts)',
  created: { digitalSourceType: DIGITAL_SOURCE.aiGenerated, softwareAgent: AGENT_NAME },
  agent: { registry: `eip155:10143:${ERC8004_IDENTITY_TESTNET}`, agentId: agentId.toString() },
}), key);
const hash = await wallet.writeContract({
  address: D.contracts.GrainRegistry, abi: registryAbi, functionName: 'register',
  args: [recordId, fp, `0x${Buffer.from(encodeSignedManifest(manifest)).toString('hex')}` as Hex],
});
await pub.waitForTransactionReceipt({ hash });
console.log(`registered record ${recordId} as AI-generated by agent #${agentId}  tx ${hash}`);
console.log(`marked image: ${OUT}`);
