import { createMcpHandler } from 'mcp-handler';
import { z } from 'zod';
import { createPublicClient, formatEther, http, type PublicClient } from 'viem';
import { FetchRefused, fetchPublicImage } from '../../lib/fetch-public';
import { checkImage } from '../../lib/verify-server';
import { loadLicensing, loadRecord } from '../../lib/record-server';
import { creatorByHandle } from '../../lib/indexer';
import { creditName } from '../../lib/agents';
import { checkProof, parseProof } from '../../lib/pen-proof';
import { LICENCE_TERMS, LICENCE_VERSION } from '../../lib/licence';
import { monadTestnet } from '../../lib/chain';

/**
 * Grain as an MCP server: any AI assistant that speaks the Model Context
 * Protocol -- Claude, ChatGPT, Cursor, an agent framework -- can ask who made
 * an image before it reposts, attributes or pays for it. Connect with the URL
 *
 *   https://grain-on-monad.vercel.app/api/mcp
 *
 * No account, wallet or key. Every tool runs the same code as the website
 * (lib/verify-server, lib/record-server), so an assistant and a person
 * checking the same image get the same answer -- and each answer carries what
 * Monad itself returned, so the assistant can cite evidence, not just Grain.
 */

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 60;

const SITE = 'https://grain-on-monad.vercel.app';
const chain = createPublicClient({ chain: monadTestnet, transport: http(process.env.RPC_TESTNET_ENDPOINT ?? process.env.NEXT_PUBLIC_RPC_URL) }) as PublicClient;
const MAX_UPLOAD = 4 * 1024 * 1024;

const text = (t: string, structured?: Record<string, unknown>) => ({
  content: [{ type: 'text' as const, text: t }], ...(structured ? { structuredContent: structured } : {}),
});
const refuse = (t: string) => ({ content: [{ type: 'text' as const, text: t }], isError: true });

const madeHow = (created?: { digitalSourceType?: string; softwareAgent?: string }, agent?: { name?: string; agentId: string; verified: boolean }) => {
  if (agent?.verified) return `AI-generated by ${agent.name ?? `agent #${agent.agentId}`} (ERC-8004 agent #${agent.agentId}, identity checked on chain)`;
  const kind = created?.digitalSourceType?.split('/').pop();
  if (kind === 'trainedAlgorithmicMedia') return `AI-generated${created?.softwareAgent ? ` with ${created.softwareAgent}` : ''}, declared by the creator`;
  if (kind === 'digitalCapture') return 'a photograph, declared by the creator';
  if (kind === 'digitalCreation') return 'artwork made by a person, declared by the creator';
  return null;
};

const handler = createMcpHandler((server) => {
  server.registerTool('verify_image', {
    title: 'Who made this image?',
    description:
      'Find out who made an image, from the image itself, even after screenshots, crops and re-encoding. ' +
      'Checks the invisible TrustMark watermark and a perceptual fingerprint against Grain, an open provenance registry on Monad. ' +
      'Returns RESOLVED (who made it), UNCERTAIN, TAMPERED (a forged credential: do not attribute it) or NOT_FOUND, plus the distance ' +
      'the Monad contract itself returned. Use before reposting, attributing, publishing or paying for an image. Pass a public image URL, ' +
      'or the image as base64 (up to 4 MB).',
    inputSchema: z.object({
      image_url: z.string().url().optional().describe('A public http(s) URL of the image'),
      image_base64: z.string().optional().describe('The image itself, base64-encoded PNG or JPEG'),
    }),
  }, async ({ image_url, image_base64 }, ctx) => {
    let bytes: Uint8Array;
    try {
      if (image_url) bytes = (await fetchPublicImage(image_url)).bytes;
      else if (image_base64) bytes = new Uint8Array(Buffer.from(image_base64.replace(/^data:[^,]+,/, ''), 'base64'));
      else return refuse('Give an image_url or image_base64.');
    } catch (e) {
      return refuse(e instanceof FetchRefused ? e.message : "Couldn't fetch that image.");
    }
    if (bytes.length > MAX_UPLOAD && !image_url) return refuse('Images sent inline are limited to 4 MB; pass a URL instead.');
    const origin = ctx.http?.req ? new URL(ctx.http.req.url).origin : SITE;
    try {
      const r = await checkImage(bytes, origin);
      const lines = [r.summary];
      if (r.record) lines.push(`Record: ${r.record.url}`);
      if (r.onChainDistance !== null) lines.push(`Checked on Monad: FingerprintIndex.verify() says the image is ${r.onChainDistance} bits from the registered fingerprint.`);
      lines.push(`Watermark: ${r.watermark}. Candidates from: ${r.candidatesFrom}.`);
      return text(lines.join('\n'), r as unknown as Record<string, unknown>);
    } catch {
      return refuse("That isn't a PNG or JPEG Grain can read, or the check couldn't finish just now.");
    }
  });

  server.registerTool('get_record', {
    title: 'A Grain record',
    description:
      'The provenance record for a Grain record number: who made it, how it was made (photo, artwork, AI-generated, or by which ERC-8004 agent), ' +
      'when it was registered on Monad, whether its signed manifest checks out, and whether and at what price it can be licensed.',
    inputSchema: z.object({ record_id: z.string().regex(/^\d{1,12}$/).describe('The record number, e.g. "536"') }),
  }, async ({ record_id }) => {
    const r = await loadRecord(record_id).catch(() => null);
    if (!r) return refuse(`There is no Grain record ${record_id}.`);
    const licensing = await loadLicensing(r.creator, record_id).catch(() => null);
    const how = madeHow(r.created, r.agent);
    const lines = [
      `Record ${record_id}${r.title ? `, "${r.title}"` : ''}: made by ${creditName(r.handle, r.agent)} (${r.creator}).`,
      ...(how ? [`How it was made: ${how}.`] : []),
      `Registered ${new Date(r.registeredAt * 1000).toISOString()}${r.blockNumber ? ` in Monad block ${r.blockNumber}` : ''}.`,
      `Manifest matches what the contract recorded: ${r.manifestMatchesChain ? 'yes' : 'no'}. Signed by the creator's key: ${r.signatureValid ? 'yes' : 'no'}.`,
      r.revoked ? 'The creator has withdrawn this record.' : r.supersededBy ? `Superseded by record ${r.supersededBy}.` : '',
      licensing && licensing.priceWei > 0n
        ? `Licensable for ${formatEther(licensing.priceWei)} MON under the ${LICENCE_VERSION} (${SITE}/licence), paid in full to the creator${licensing.licences ? `; ${licensing.licences} licence(s) so far` : ''}.`
        : 'Not offered for licensing.',
      `${SITE}/r/${record_id}${r.txHash ? `\nTransaction: https://testnet.monadscan.com/tx/${r.txHash}` : ''}`,
    ].filter(Boolean);
    return text(lines.join('\n'));
  });

  server.registerTool('get_creator', {
    title: 'A creator on Grain',
    description: "A creator's public page on Grain: how many images they have registered, what licences of their work have earned, and their latest records.",
    inputSchema: z.object({ handle: z.string().regex(/^@?[a-z0-9-]{1,32}$/).describe('The creator handle, e.g. "grain-studio"') }),
  }, async ({ handle }) => {
    const h = handle.replace(/^@/, '');
    const c = await creatorByHandle(h);
    if (c === 'unavailable') return refuse("Grain's indexer isn't answering just now. Try again shortly.");
    if (!c) return refuse(`No creator is called @${h} on Grain.`);
    const earned = c.licences.reduce((s, l) => s + BigInt(l.amountWei), 0n);
    return text([
      `@${c.handle} (${c.address}): ${c.recordCount} image(s) registered; ${c.licences.length} licence(s) sold, ${formatEther(earned)} MON earned.`,
      `Latest records: ${c.records.slice(0, 10).map((r) => `#${r.recordId}`).join(', ') || 'none'}.`,
      `${SITE}/c/${c.handle}`,
    ].join('\n'));
  });

  server.registerTool('check_pen_proof', {
    title: 'Check a pen-name proof',
    description:
      'Verify a Grain pen-name proof link: a creator showing that a pen name is theirs. Checks the commitment the pen name recorded on Monad ' +
      "and the creator identity's signature. Every other pen name of theirs stays unlinkable.",
    inputSchema: z.object({ proof_url: z.string().url().describe('The proof link, e.g. https://grain-on-monad.vercel.app/proof?pen=…') }),
  }, async ({ proof_url }) => {
    const proof = parseProof(new URL(proof_url).searchParams);
    if (!proof) return refuse("That link isn't a complete pen-name proof.");
    const r = await checkProof(chain, proof).catch(() => null);
    if (!r) return refuse("Couldn't reach Monad just now.");
    if (!r.ok) return text(`Not proven. ${r.reason}`);
    const who = r.identityHandle ? `@${r.identityHandle}` : r.identity;
    return text(`Proven: @${r.penHandle} is ${who}. The commitment @${r.penHandle} recorded on Monad matches, and ${who}'s identity signed the proof on ${new Date(r.issuedAt * 1000).toISOString()}.`);
  });

  server.registerTool('get_licence_terms', {
    title: 'Grain licence terms',
    description: `What a Grain licence (${LICENCE_VERSION}) lets the licensee do with an image.`,
    inputSchema: z.object({}),
  }, async () => text(`${LICENCE_VERSION} (${SITE}/licence)\n${LICENCE_TERMS.map(([t, d]) => `- ${t}: ${d}`).join('\n')}\n` +
    'Testnet draft in plain language, not legal advice.'));
}, {
  serverInfo: { name: 'grain', version: '1.0.0' },
  instructions:
    'Grain is an open provenance registry for images, on the Monad blockchain. Before you repost, attribute, publish or pay for an image, ' +
    'call verify_image. If the answer is TAMPERED, the image carries someone else\'s credential: do not attribute it to them. ' +
    "Cite the creator by handle and link to their record, and mention how the image was made when the record says.",
});

export { handler as GET, handler as POST, handler as DELETE };
